# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import glossary_pb2 as protos_dot_glossary__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/glossary_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GlossaryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllTerms = channel.unary_unary(
                '/glossary.GlossaryService/GetAllTerms',
                request_serializer=protos_dot_glossary__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_glossary__pb2.TermsList.FromString,
                _registered_method=True)
        self.GetTerm = channel.unary_unary(
                '/glossary.GlossaryService/GetTerm',
                request_serializer=protos_dot_glossary__pb2.GetTermRequest.SerializeToString,
                response_deserializer=protos_dot_glossary__pb2.Term.FromString,
                _registered_method=True)
        self.CreateTerm = channel.unary_unary(
                '/glossary.GlossaryService/CreateTerm',
                request_serializer=protos_dot_glossary__pb2.CreateTermRequest.SerializeToString,
                response_deserializer=protos_dot_glossary__pb2.Term.FromString,
                _registered_method=True)
        self.UpdateTerm = channel.unary_unary(
                '/glossary.GlossaryService/UpdateTerm',
                request_serializer=protos_dot_glossary__pb2.UpdateTermRequest.SerializeToString,
                response_deserializer=protos_dot_glossary__pb2.Term.FromString,
                _registered_method=True)
        self.DeleteTerm = channel.unary_unary(
                '/glossary.GlossaryService/DeleteTerm',
                request_serializer=protos_dot_glossary__pb2.DeleteTermRequest.SerializeToString,
                response_deserializer=protos_dot_glossary__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.CreateRelationship = channel.unary_unary(
                '/glossary.GlossaryService/CreateRelationship',
                request_serializer=protos_dot_glossary__pb2.CreateRelationshipRequest.SerializeToString,
                response_deserializer=protos_dot_glossary__pb2.RelationshipResponse.FromString,
                _registered_method=True)
        self.GetGraph = channel.unary_unary(
                '/glossary.GlossaryService/GetGraph',
                request_serializer=protos_dot_glossary__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_glossary__pb2.GraphResponse.FromString,
                _registered_method=True)


class GlossaryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllTerms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTerm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTerm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTerm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTerm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRelationship(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GlossaryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllTerms': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllTerms,
                    request_deserializer=protos_dot_glossary__pb2.Empty.FromString,
                    response_serializer=protos_dot_glossary__pb2.TermsList.SerializeToString,
            ),
            'GetTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTerm,
                    request_deserializer=protos_dot_glossary__pb2.GetTermRequest.FromString,
                    response_serializer=protos_dot_glossary__pb2.Term.SerializeToString,
            ),
            'CreateTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTerm,
                    request_deserializer=protos_dot_glossary__pb2.CreateTermRequest.FromString,
                    response_serializer=protos_dot_glossary__pb2.Term.SerializeToString,
            ),
            'UpdateTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTerm,
                    request_deserializer=protos_dot_glossary__pb2.UpdateTermRequest.FromString,
                    response_serializer=protos_dot_glossary__pb2.Term.SerializeToString,
            ),
            'DeleteTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTerm,
                    request_deserializer=protos_dot_glossary__pb2.DeleteTermRequest.FromString,
                    response_serializer=protos_dot_glossary__pb2.DeleteResponse.SerializeToString,
            ),
            'CreateRelationship': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRelationship,
                    request_deserializer=protos_dot_glossary__pb2.CreateRelationshipRequest.FromString,
                    response_serializer=protos_dot_glossary__pb2.RelationshipResponse.SerializeToString,
            ),
            'GetGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGraph,
                    request_deserializer=protos_dot_glossary__pb2.Empty.FromString,
                    response_serializer=protos_dot_glossary__pb2.GraphResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'glossary.GlossaryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('glossary.GlossaryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GlossaryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllTerms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.GlossaryService/GetAllTerms',
            protos_dot_glossary__pb2.Empty.SerializeToString,
            protos_dot_glossary__pb2.TermsList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.GlossaryService/GetTerm',
            protos_dot_glossary__pb2.GetTermRequest.SerializeToString,
            protos_dot_glossary__pb2.Term.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.GlossaryService/CreateTerm',
            protos_dot_glossary__pb2.CreateTermRequest.SerializeToString,
            protos_dot_glossary__pb2.Term.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.GlossaryService/UpdateTerm',
            protos_dot_glossary__pb2.UpdateTermRequest.SerializeToString,
            protos_dot_glossary__pb2.Term.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.GlossaryService/DeleteTerm',
            protos_dot_glossary__pb2.DeleteTermRequest.SerializeToString,
            protos_dot_glossary__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRelationship(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.GlossaryService/CreateRelationship',
            protos_dot_glossary__pb2.CreateRelationshipRequest.SerializeToString,
            protos_dot_glossary__pb2.RelationshipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.GlossaryService/GetGraph',
            protos_dot_glossary__pb2.Empty.SerializeToString,
            protos_dot_glossary__pb2.GraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
